name: "Prepare for Build with Apache Maven"
description: "Restores the Apache Maven local repository, checks out code and installs Java in preparation for Maven build"

branding:
  icon: more-horizontal
  color: purple

inputs:
  java-version:
    description: Java version
    required: true
    default: 8
  checkout-branch:
    description: git branch to checkout
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - id: cache-m2
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - id: cache-ivy2
      name: Cache Ivy packages
      uses: actions/cache@v3
      with:
        path: ~/.ivy2
        key: ${{ runner.os }}-ivy2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-ivy2
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ checkout-branch }}
    - id: setup-java
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
        server-id: sonatype-nexus
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - id: show-environment
      name: Show environment
      shell: bash
      run: |
        # Show environment
        echo operating system: ${{ runner.os }}
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        echo java:
        java -version
        echo maven:
        mvn -v
        cat ~/.m2/settings.xml
        which dot || echo "Graphviz not installed"
